import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Montserrat } from "next/font/google";

import './globals.css'
import Navbar from '@/components/ui/nav'
import Router from 'next/router';
const inter = Inter({ subsets: ['latin'] })
const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'WebChips || Home',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Navbar />
        {children}
      </body>
      
    </html>
  )
}
